python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/lysosome_te.csv --checkpoint_dir saved_models/lysosome --preds_path test_predict_results/lysosome.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/nuclear_membrane_te.csv --checkpoint_dir saved_models/nuclear_membrane --preds_path test_predict_results/nuclear_membrane.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/endoplasmic_reticulum_te.csv --checkpoint_dir saved_models/endoplasmic_reticulum --preds_path test_predict_results/endoplasmic_reticulum.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/mitochondria_te.csv --checkpoint_dir saved_models/mitochondria --preds_path test_predict_results/mitochondria.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/microtubules_te.csv --checkpoint_dir saved_models/microtubules --preds_path test_predict_results/microtubules.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/er_membrane_te.csv --checkpoint_dir saved_models/er_membrane --preds_path test_predict_results/er_membrane.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/cytokinetic_bridge_te.csv --checkpoint_dir saved_models/cytokinetic_bridge --preds_path test_predict_results/cytokinetic_bridge.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/peroxisome_te.csv --checkpoint_dir saved_models/peroxisome --preds_path test_predict_results/peroxisome.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/nuclear_speckles_te.csv --checkpoint_dir saved_models/nuclear_speckles --preds_path test_predict_results/nuclear_speckles.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/vesicles_te.csv --checkpoint_dir saved_models/vesicles --preds_path test_predict_results/vesicles.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/plasma_membrane_te.csv --checkpoint_dir saved_models/plasma_membrane --preds_path test_predict_results/plasma_membrane.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/endosome_te.csv --checkpoint_dir saved_models/endosome --preds_path test_predict_results/endosome.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/er_lumen_te.csv --checkpoint_dir saved_models/er_lumen --preds_path test_predict_results/er_lumen.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/mitochondrial_protein_te.csv --checkpoint_dir saved_models/mitochondrial_protein --preds_path test_predict_results/mitochondrial_protein.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/midbody_te.csv --checkpoint_dir saved_models/midbody --preds_path test_predict_results/midbody.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/nucleoli_fibrillar_center_te.csv --checkpoint_dir saved_models/nucleoli_fibrillar_center --preds_path test_predict_results/nucleoli_fibrillar_center.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/membrane_protein_te.csv --checkpoint_dir saved_models/membrane_protein --preds_path test_predict_results/membrane_protein.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/cytosol_te.csv --checkpoint_dir saved_models/cytosol --preds_path test_predict_results/cytosol.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/secreted_te.csv --checkpoint_dir saved_models/secreted --preds_path test_predict_results/secreted.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/vesicle_membrane_te.csv --checkpoint_dir saved_models/vesicle_membrane --preds_path test_predict_results/vesicle_membrane.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/nucleus_te.csv --checkpoint_dir saved_models/nucleus --preds_path test_predict_results/nucleus.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/nucleoplasm_te.csv --checkpoint_dir saved_models/nucleoplasm --preds_path test_predict_results/nucleoplasm.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/golgi_apparatus_te.csv --checkpoint_dir saved_models/golgi_apparatus --preds_path test_predict_results/golgi_apparatus.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/intermediate_filaments_te.csv --checkpoint_dir saved_models/intermediate_filaments --preds_path test_predict_results/intermediate_filaments.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/golgi_lumen_te.csv --checkpoint_dir saved_models/golgi_lumen --preds_path test_predict_results/golgi_lumen.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/centrosome_te.csv --checkpoint_dir saved_models/centrosome --preds_path test_predict_results/centrosome.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/actin_filaments_te.csv --checkpoint_dir saved_models/actin_filaments --preds_path test_predict_results/actin_filaments.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/mitochondrial_membrane_te.csv --checkpoint_dir saved_models/mitochondrial_membrane --preds_path test_predict_results/mitochondrial_membrane.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/focal_adhesions_te.csv --checkpoint_dir saved_models/focal_adhesions --preds_path test_predict_results/focal_adhesions.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/microtubule_organizing_center_te.csv --checkpoint_dir saved_models/microtubule_organizing_center --preds_path test_predict_results/microtubule_organizing_center.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/lysosomal_membrane_te.csv --checkpoint_dir saved_models/lysosomal_membrane --preds_path test_predict_results/lysosomal_membrane.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/cell_junctions_te.csv --checkpoint_dir saved_models/cell_junctions --preds_path test_predict_results/cell_junctions.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/cytoplasmic_bodies_te.csv --checkpoint_dir saved_models/cytoplasmic_bodies --preds_path test_predict_results/cytoplasmic_bodies.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/mitotic_spindle_te.csv --checkpoint_dir saved_models/mitotic_spindle --preds_path test_predict_results/mitotic_spindle.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/cytoskeleton_te.csv --checkpoint_dir saved_models/cytoskeleton --preds_path test_predict_results/cytoskeleton.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/golgi_membrane_te.csv --checkpoint_dir saved_models/golgi_membrane --preds_path test_predict_results/golgi_membrane.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/rods_and_rings_te.csv --checkpoint_dir saved_models/rods_and_rings --preds_path test_predict_results/rods_and_rings.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/nucleoli_te.csv --checkpoint_dir saved_models/nucleoli --preds_path test_predict_results/nucleoli.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/endosomal_membrane_te.csv --checkpoint_dir saved_models/endosomal_membrane --preds_path test_predict_results/endosomal_membrane.csv
python3 ../predict.py --test_path dataset/splitted_csv_files_mpnn_models/nuclear_bodies_te.csv --checkpoint_dir saved_models/nuclear_bodies --preds_path test_predict_results/nuclear_bodies.csv
